# Generated by Django 5.1.6 on 2025-02-10 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_options', models.CharField(choices=[('ALL_PAYMENTS', 'All_Payments'), ('ALL_TRANSACTIONS', 'All_Transactions')], max_length=20)),
                ('file_name', models.CharField(max_length=100)),
                ('date_range', models.CharField(max_length=100)),
                ('columns', models.JSONField(default=list)),
                ('sheet_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
