# Generated by Django 5.1.6 on 2025-02-10 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataMapper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='export',
            old_name='export_options',
            new_name='export_type',
        ),
    ]
